[development]
address = "127.0.0.1"
port = 8000
workers = 16
log = "critical"
limits = { forms = 32768 }

[production]
address = "127.0.0.1"
port = 80
workers = 16
log = "critical"
limits = { forms = 32768 }